### ISSUE TITLE
Loading zipped shapefiles on Windows

### ISSUE THREAD

**Issue by turnerm** [OCHA-DAP/pa-aa-toolbox#123]
@PaulineNimo found the following bug on Windows when running `codab.load()`:

```
Traceback (most recent call last):
  File "fiona\_shim.pyx", line 83, in fiona._shim.gdal_open_vector
  File "fiona\_err.pyx", line 291, in fiona._err.exc_wrap_pointer
fiona._err.CPLE_OpenFailedError: '/vsizip//G:\Shared drives\Predictive Analytics\CERF Anticipatory Action\General - All AA projects\Data\public\raw\npl\cod_ab\npl_cod_ab.shp.zip\npl_admbnda_adm1_nd_20201117.shp' does not exist in the file system, and is not recognized as a supported dataset name.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\pauni\Desktop\Work\OCHA\Nepal\analysis\nplanalysis\lib\site-packages\aatoolbox\datasources\codab\codab.py", line 162, in _load_admin_layer
    return gpd.read_file(f"zip:///{self._raw_filepath / layer_name}")
  File "C:\Users\pauni\Desktop\Work\OCHA\Nepal\analysis\nplanalysis\lib\site-packages\geopandas\io\file.py", line 201, in _read_file
    with reader(path_or_bytes, **kwargs) as features:
  File "C:\Users\pauni\Desktop\Work\OCHA\Nepal\analysis\nplanalysis\lib\site-packages\fiona\env.py", line 408, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\pauni\Desktop\Work\OCHA\Nepal\analysis\nplanalysis\lib\site-packages\fiona\__init__.py", line 267, in open
    c = Collection(path, mode, driver=driver, encoding=encoding,
  File "C:\Users\pauni\Desktop\Work\OCHA\Nepal\analysis\nplanalysis\lib\site-packages\fiona\collection.py", line 162, in __init__
    self.session.start(self, **kwargs)
  File "fiona\ogrext.pyx", line 540, in fiona.ogrext.Session.start
  File "fiona\_shim.pyx", line 90, in fiona._shim.gdal_open_vector
fiona.errors.DriverError: '/vsizip//G:\Shared drives\Predictive Analytics\CERF Anticipatory Action\General - All AA projects\Data\public\raw\npl\cod_ab\npl_cod_ab.shp.zip\npl_admbnda_adm1_nd_20201117.shp' does not exist in the file system, and is not recognized as a supported dataset name.      

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\pauni\Desktop\Work\OCHA\Nepal\analysis\toolboxtest.py", line 11, in <module>
    provinces = codab.load(admin_level=1)
  File "C:\Users\pauni\Desktop\Work\OCHA\Nepal\analysis\nplanalysis\lib\site-packages\aatoolbox\datasources\codab\codab.py", line 110, in load      
    return self._load_admin_layer(
  File "C:\Users\pauni\Desktop\Work\OCHA\Nepal\analysis\nplanalysis\lib\site-packages\aatoolbox\datasources\codab\codab.py", line 164, in _load_admin_layer
    raise FileNotFoundError(
FileNotFoundError: Could not read boundary shapefile. Make sure that you have already called the 'download' method and that the file G:\Shared drives\Predictive Analytics\CERF Anticipatory Action\General - All AA projects\Data\public\raw\npl\cod_ab\npl_cod_ab.shp.zip exists. If it does exist, please check the validity of the layer name: 'npl_admbnda_adm1_nd_20201117.shp'
```
I think the problem is in [this line](https://github.com/OCHA-DAP/pa-aa-toolbox/blob/main/src/aatoolbox/datasources/codab/codab.py#L162), it could be fixed by removing a slash for zip, but may also need to use all forward slashes with `Path.as_posix()`.

I'm wondering how to avoid such bugs in the future, this wouldn't have been caught in the unit tests, but we should at some point implement end-to-end across platforms. At any rate not sure if it's worth running the unit tests on mac and windows, it would be a bit of a pain though because of GDAL installation.

**Comment by Tinkaa** [comment]
Good catch! (and weird [geopandas docs](https://geopandas.org/en/v0.8.2/io.html) doesnt flag this). 

Bit the larger question of testing on different operation systems is a toughy. I think in principle it makes sense.. Is the pain in GDAL with test running time or hard to implement as part of the flow? 
If the first, we could maybe only test for one python version on Mac and Windows. Or only run the tests on Mac and Linux with a new release? (I know this is a bit of a cheat)

**Comment by turnerm** [comment]
close with #124

**Comment by turnerm** [comment]
Oops, I didn't answer you @Tinkaa:

> Bit the larger question of testing on different operation systems is a toughy. I think in principle it makes sense.. Is the pain in GDAL with test running time or hard to implement as part of the flow?

I think both, would need to work on setting up a Windows environment in GitHub Actions with GDAL which I am not looking forward to. But also the tests will take longer if we are doing 3 x as many (not sure how far the parallelization goes)

> If the first, we could maybe only test for one python version on Mac and Windows. Or only run the tests on Mac and Windows with a new release? (I know this is a bit of a cheat)

That's a good idea! Maybe put some e2e tests for the release branch, on all OSs.
